import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

/**
 * Every route this app navigates to must exist.
 *
 * ## Why this file exists at all
 *
 * `app/food/target.tsx` shipped a button that called `router.push('/profile')`.
 * There is no `/profile` — there is `/profile/edit`, and there never was an
 * index beside it. So the single action on a screen whose whole job is to
 * explain why it cannot compute a target sent the athlete to `+not-found`.
 *
 * **Nothing could have caught it, and that is the interesting part.** Expo
 * Router's typed routes are real and would have flagged it — but they are
 * GENERATED by Metro into `.expo/`, which is gitignored. CI checks out a clean
 * tree, never starts Metro, and `tsc` therefore sees `Href` as a loose string
 * and passes. The bug surfaced only because one worktree happened to have a
 * generated `router.d.ts` lying around from a dev-server run.
 *
 * So the type system's guarantee here is real locally and absent in CI, which
 * is the worst of the three possible states: it looks covered. This test is the
 * part that runs everywhere.
 *
 * ## What it does NOT do
 *
 * It reads string literals only. A route assembled at runtime —
 * `` router.push(`/session/${id}`) `` — has no literal to check, and the
 * template's static prefix is deliberately not half-matched, because a partial
 * check that reports a pass is worse than no check. Dynamic segments in the
 * ROUTE tree are matched (`/session/[id]` accepts `/session/abc`), so a literal
 * pointing into a dynamic route is covered; a computed one is not.
 *
 * If this ever needs to be stronger, the honest upgrade is generating the typed
 * routes in CI and letting `tsc` do it properly — not making this regex
 * cleverer.
 */

const MOBILE = join(__dirname, '..', '..');
const APP = join(MOBILE, 'app');

/** Files Expo Router does not turn into routes. */
function isRouteFile(name: string): boolean {
  return name.endsWith('.tsx') && !name.startsWith('_layout') && !name.startsWith('+');
}

function walk(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      if (entry === '__tests__' || entry === 'node_modules') continue;
      walk(full, out);
    } else {
      out.push(full);
    }
  }
  return out;
}

/**
 * Every path the router will actually resolve.
 *
 * Two spellings per file, because both are legal and both are used here: a
 * group is invisible in a URL (`app/(tabs)/workouts.tsx` → `/workouts`) but may
 * also be named explicitly (`/(tabs)/workouts`), which this app does in three
 * places. Emitting only the stripped form would fail those three and teach
 * whoever hit it that the test is noise.
 */
function routes(): string[] {
  const all: string[] = [];
  for (const file of walk(APP)) {
    const name = file.split(sep).pop() ?? '';
    if (!isRouteFile(name)) continue;
    let route = '/' + relative(APP, file).split(sep).join('/').replace(/\.tsx$/, '');
    if (route.endsWith('/index')) route = route.slice(0, -'/index'.length);
    all.push(route || '/');
    const stripped = route.replace(/\/\([^)]*\)/g, '');
    all.push(stripped || '/');
  }
  return [...new Set(all)];
}

/**
 * A route pattern matches a literal when its dynamic segments are filled.
 *
 * Built segment by segment rather than by one `replace`, and that is not
 * style: a group route contains `(` and `)`, which a naive `new RegExp` reads
 * as a CAPTURE GROUP — so `/(tabs)/workouts` compiled to a pattern matching
 * `/tabs/workouts` and reported the three real, working, group-qualified pushes
 * in this app as dead. A guard whose first run cries wolf gets deleted.
 */
function resolves(target: string, all: string[]): boolean {
  const path = target.split('?')[0].split('#')[0].replace(/\/$/, '') || '/';
  return all.some((r) => {
    const pattern = r
      .split('/')
      .map((seg) =>
        /^\[.+\]$/.test(seg) ? '[^/]+' : seg.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'),
      )
      .join('/');
    return new RegExp(`^${pattern}$`).test(path);
  });
}

/** Where a navigation begins. The literals may be anywhere inside it. */
const NAVIGATION_START = /(?:router|nav)\.(?:push|replace|navigate)\s*\(|href=\{?/g;

/** A quoted path literal — `'/profile/edit'`, `"/workouts"`. */
const PATH_LITERAL = /['"](\/[^'"`$\s]*)['"]/g;

/**
 * Every route literal inside a navigation expression.
 *
 * Scans the whole call rather than only what sits immediately after the open
 * paren, and that is the difference between a guard and a decoration. The first
 * version matched `router.push('/x')` and nothing else — so the moment this
 * repo's own fix put the path behind a ternary
 * (`router.push(cond ? '/a' : '/b')`), the test went green against a
 * deliberately reintroduced `/profile`. It was checking a shape no longer used
 * by the code it existed for.
 *
 * Balanced to the close paren so a literal from the NEXT statement cannot be
 * attributed to this one; `href=` has no parens, so it takes the rest of the
 * line, which is where a JSX attribute's value lives.
 */
function targetsIn(src: string): string[] {
  const found: string[] = [];
  for (const start of src.matchAll(NAVIGATION_START)) {
    const from = (start.index ?? 0) + start[0].length;
    let span: string;
    if (start[0].endsWith('(')) {
      let depth = 1;
      let i = from;
      for (; i < src.length && depth > 0; i++) {
        if (src[i] === '(') depth++;
        else if (src[i] === ')') depth--;
      }
      span = src.slice(from, i);
    } else {
      span = src.slice(from, src.indexOf('\n', from) + 1 || undefined);
    }
    for (const m of span.matchAll(PATH_LITERAL)) found.push(m[1]);
  }
  return found;
}

describe('navigation targets', () => {
  const all = routes();

  it('finds the route tree at all', () => {
    // Guards the guard: a walk that silently returned nothing would make every
    // assertion below vacuous, and this file would read as covering the app
    // while checking an empty set.
    expect(all.length).toBeGreaterThan(30);
    expect(all).toContain('/profile/edit');
    expect(existsSync(join(APP, 'food', 'target.tsx'))).toBe(true);
  });

  it('never points at a route that does not exist', () => {
    const dead: string[] = [];
    for (const dir of ['app', 'components']) {
      for (const file of walk(join(MOBILE, dir))) {
        if (!/\.tsx?$/.test(file)) continue;
        for (const target of targetsIn(readFileSync(file, 'utf8'))) {
          if (!resolves(target, all)) dead.push(`${relative(MOBILE, file)} → ${target}`);
        }
      }
    }
    // Named rather than counted, so a failure says which button is broken.
    expect(dead).toEqual([]);
  });
});
