import { describe, expect, it } from "vitest";

import {
  formatFluid,
  formatGirth,
  formatHeight,
  formatWeight,
  fromDisplayWeight,
  fromFeetInches,
  toDisplayWeight,
  toFeetInches,
} from "@/lib/units";

/**
 * A smoke test for the GENERATED units module — deliberately small.
 *
 * `apps/web/src/lib/units.ts` is generated byte-for-byte from
 * `apps/mobile/lib/units.ts` by `scripts/sync-units.py`, and `check:units`
 * fails in `verify` and in CI if it is not. The arithmetic is therefore covered
 * once, thoroughly, at the source: `apps/mobile/lib/__tests__/units.test.ts`
 * sweeps every displayed value in both systems for all five quantities.
 * Re-running those loops here would be running the same code twice.
 *
 * What this file is for is the thing that check CANNOT see: that the generated
 * file is a valid TypeScript module **in this app** — that it imports through
 * `@/lib/units`, that its exports are the names web's screens use, and that a
 * conversion actually runs under vitest. A generator that emitted a truncated
 * or syntactically broken file would still satisfy a byte-comparison against
 * whatever it had just written; only importing it proves otherwise.
 *
 * The fluid functions are asserted by name on purpose. Their absence from
 * web's old hand-maintained copy is the drift that motivated N105 — mobile
 * could render a volume in the athlete's own units and web could not — so
 * their presence here is the specific regression being pinned.
 */
describe("the generated units module", () => {
  it("converts weight in both directions", () => {
    expect(toDisplayWeight(100, "imperial")).toBe(220.5);
    expect(toDisplayWeight(100, "metric")).toBe(100);
    expect(fromDisplayWeight(220.5, "imperial")).toBeCloseTo(100.017, 3);
    // Not merely "different" — a conversion applied the wrong way would also
    // be different, and would also be wrong.
    expect(fromDisplayWeight(100, "imperial")).toBeLessThan(100);
  });

  it("carries the height support web never had", () => {
    expect(fromFeetInches(5, 11)).toBe(180.3);
    expect(toFeetInches(180.3)).toEqual({ feet: 5, inches: 11 });
    expect(formatHeight(180.3, "imperial")).toBe(`5'11"`);
    expect(formatHeight(180, "metric")).toBe("180 cm");
  });

  it("carries the girth support web never had", () => {
    expect(formatGirth(82.6, "imperial")).toBe("32.5 in");
    expect(formatGirth(82.6, "metric")).toBe("82.6 cm");
  });

  it("carries the fluid functions that were missing from the hand-copy", () => {
    expect(formatFluid(2000, "metric")).toBe("2 L");
    expect(formatFluid(2000, "imperial")).toBe("67.6 fl oz");
  });

  it("formats an absent value rather than throwing", () => {
    expect(formatWeight(null, "metric")).toBe("—");
    expect(formatHeight(null, "imperial")).toBe("—");
    expect(formatFluid(undefined, "metric")).toBe("—");
  });
});
