import type { Href } from 'expo-router';

import { logsAfterwards, type Module } from './modules';

/**
 * Where a chosen discipline goes when the athlete says "log this".
 *
 * ## Why it is a function and not two `router.push` calls
 *
 * `PickSessionSheet` returns a `Pick` and leaves navigating to its caller. It
 * had one caller that navigated (Today) and one that did not (the week
 * planner, which writes a plan instead). N176 gave the Train tab the same
 * action, and a second copy of a two-branch route decision is precisely how
 * this app ended up with three disagreeing sport lists — the thing the module
 * registry exists to stop. So the branch is written once, here.
 *
 * ## The branch itself
 *
 * A discipline that logs AFTER the fact cannot be started and logged into, so
 * it goes to its own log screen rather than to the set logger. Asked through
 * `logsAfterwards`, which reads the catalog kind rather than the module key —
 * a second technique-shaped discipline should get the right flow without this
 * file learning its name. Sending one to `/session/start` renders a set logger
 * over a session that can never hold a set.
 *
 * ## The return type is doing real work
 *
 * `Href`, not `string`. Expo Router's typed routes are generated by Metro into
 * `.expo/types`, and a helper returning a bare `string` would launder the
 * literals below past them — `router.push(someString)` type-checks against
 * anything. Declaring the return as `Href` puts the check back where the
 * literals are written, which is the only place it can be made. See N32 and the
 * `typecheck:mobile` step that regenerates those types.
 */
export function startSessionHref(
  pick: { sport: string; workoutId: string | null },
  modules: Module[],
): Href {
  if (logsAfterwards(pick.sport, modules)) return '/bjj/log';
  return pick.workoutId
    ? `/session/start?sport=${pick.sport}&workout=${pick.workoutId}`
    : `/session/start?sport=${pick.sport}`;
}
