import type { Href } from 'expo-router';

import { logsAfterwards, type Module } from './modules';

/**
 * Where a chosen discipline goes when the athlete says "log this".
 *
 * ## Why it is a function and not two `router.push` calls
 *
 * `PickSessionSheet` returns a `Pick` and leaves navigating to its caller. It
 * had one caller that navigated (Today) and one that did not (the week
 * planner, which writes a plan instead). N176 gave the Train tab the same
 * action, and a second copy of a two-branch route decision is precisely how
 * this app ended up with three disagreeing sport lists — the thing the module
 * registry exists to stop. So the branch is written once, here.
 *
 * ## The branch itself
 *
 * A discipline that logs AFTER the fact cannot be started and logged into, so
 * it goes to its own log screen rather than to the set logger. Asked through
 * `logsAfterwards`, which reads the catalog kind rather than the module key —
 * a second technique-shaped discipline should get the right flow without this
 * file learning its name. Sending one to `/session/start` renders a set logger
 * over a session that can never hold a set.
 *
 * ## The return type is doing real work
 *
 * `Href`, not `string`. Expo Router's typed routes are generated by Metro into
 * `.expo/types`, and a helper returning a bare `string` would launder the
 * literals below past them — `router.push(someString)` type-checks against
 * anything. Declaring the return as `Href` puts the check back where the
 * literals are written, which is the only place it can be made. See N32 and the
 * `typecheck:mobile` step that regenerates those types.
 */
export function startSessionHref(
  pick: { sport: string; workoutId: string | null },
  modules: Module[],
  /**
   * A day key (`YYYY-MM-DD`), when this is backfilling a day other than
   * today (N434/#721) — carried through as `?date=`, matching the
   * `?date=` convention `momentumLogFoodHref`/`momentumOpenFoodHref`
   * already use in `lib/todayBoard.ts` for the same "which day is this
   * for" question. Absent on the ordinary path, so an existing caller that
   * never passes a third argument gets the exact same `Href` as before.
   */
  date?: string,
): Href {
  if (logsAfterwards(pick.sport, modules)) {
    return date ? `/bjj/log?date=${date}` : '/bjj/log';
  }
  // Four literal-prefixed template branches rather than building the query
  // string up through an intermediate `base` variable: Expo Router's typed
  // routes check the LITERAL text of the template against the generated
  // pattern, and a `base` already widened to plain `string` by an earlier
  // interpolation cannot be narrowed back — `${base}&date=${date}` fails
  // typecheck even though every branch it could produce is a real route.
  if (pick.workoutId && date) {
    return `/session/start?sport=${pick.sport}&workout=${pick.workoutId}&date=${date}`;
  }
  if (pick.workoutId) {
    return `/session/start?sport=${pick.sport}&workout=${pick.workoutId}`;
  }
  if (date) {
    return `/session/start?sport=${pick.sport}&date=${date}`;
  }
  return `/session/start?sport=${pick.sport}`;
}

/**
 * Where an EXISTING session opens — resuming it, or reading one back.
 *
 * The sibling of {@link startSessionHref} and keyed on the same predicate, for
 * the same reason one level along: a discipline whose sessions cannot hold a
 * set gets a screen that can never be filled, and the live set logger renders
 * "Sets 0 · Reps 0 · Volume —" over an empty list. That shipped once, and the
 * damage was larger than a wrong screen — the BJJ reflection wizard is entered
 * by `replace` from the log screen and linked from nowhere else, so a logged
 * class had no surface anywhere that would ever show it back.
 *
 * It lived inline in Today, which was fine while Today was the only screen that
 * opened a session. N177 gives Train a Resume card and a Recent list, both of
 * which open one, and a second copy of this branch is how the two surfaces end
 * up disagreeing about where a BJJ session lives. Moved here beside the start
 * branch rather than copied, so the pair can only ever agree.
 *
 * ## The object form is deliberate
 *
 * `{ pathname, params }` rather than a template string. Expo Router's typed
 * routes reject a bare `string`, and going through the generated pathname
 * literals means a renamed route breaks the build instead of the tap — the same
 * argument the `Href` return type above makes, arrived at from the other side.
 */
export function sessionHref(s: { id: string; sport: string }, modules: Module[]): Href {
  return logsAfterwards(s.sport, modules)
    ? ({ pathname: '/bjj/session/[id]', params: { id: s.id } } as const)
    : ({ pathname: '/session/[id]', params: { id: s.id } } as const);
}
