import { RADIUS_SCALE, SPACING_SCALE, PILL_RADIUS } from '@/constants/designTokens.generated';

/**
 * The VOLA mobile spacing and radius scale.
 *
 * Sibling to `Colors.ts` — same idea (facts about the brand live in one file
 * and code references them, never restates them), same reason it exists:
 * `assets/brand/design-tokens.json` declared a spacing scale from the start
 * and nothing in `apps/mobile` ever imported it. Every screen picked its own
 * numbers by eye, and N508's audit measured the result — 1,969 spacing
 * literals (`padding*`/`margin*`/`gap`) across `app/` + `components/`, 54% of
 * them off the scale the brand file already declared. The two values the app
 * converged on independently, a 20pt screen gutter and a 14pt card padding,
 * were not even ON that scale — the app organically settled on numbers the
 * brand file didn't list.
 *
 * ## The scale was widened, not the app snapped to fit it (N508)
 *
 * `design-tokens.json`'s original scale was `[4, 8, 12, 16, 24, 32, 48, 64]`
 * — a 4pt-and-up step. Measured real usage across the six screens converted
 * by this ticket (`components/ui/Stat.tsx`, `ScreenHeader.tsx`,
 * `(tabs)/workouts.tsx`, `(tabs)/progress.tsx`, `running/[id].tsx`,
 * `bjj/session/[id].tsx`, `session/[id].tsx`) put real, load-bearing weight on
 * 2, 6, 10, 14 and 20 as well — none of which that scale admits. Forcing
 * ~half the app's spacing to the nearest declared step would have been an
 * enormous, largely invisible-per-site but massive-in-aggregate visual
 * shift, for a scale that turned out to be too coarse rather than a set of
 * screens that were wrong. So `design-tokens.json`'s `spacing` array was
 * widened to `[2, 4, 6, 8, 10, 12, 14, 16, 20, 24, 32, 48, 64]` — a 2pt step
 * through the low range, where the real disagreement was, coarsening back to
 * the original step once past 24. Same reasoning for `radius`: 14 was
 * already the de facto card radius (112 sites, `Stat.tsx`'s own `row` style
 * included) and not on the declared `[8, 12, 16, 24]` — added rather than
 * fought, giving `[8, 12, 14, 16, 24]`.
 *
 * ## Where the raw numbers come from
 *
 * `constants/designTokens.generated.ts`, generated by
 * `scripts/generate_design_tokens.mjs` from `assets/brand/design-tokens.json`
 * — see that script's own comment for why a generated file rather than a
 * direct JSON import (the brand kit sits outside `apps/mobile`, and nothing
 * widens Metro's watch roots to reach it). This file is where the generated
 * numbers get names, doc comments and the semantic groupings screens
 * actually reach for; nothing outside this file and `Typography.ts` should
 * import the generated module directly.
 */
export const Spacing = {
  /** 2pt. The smallest deliberate gap — an icon hugging its label. */
  xxs: SPACING_SCALE[0],
  /** 4pt. A tight gap inside a compact row (`Stat`'s divider inset, a badge's icon gap). */
  xs: SPACING_SCALE[1],
  /** 6pt. Between a label and the thing it's labelling, closer than `sm`. */
  xsPlus: SPACING_SCALE[2],
  /** 8pt. The standard small gap — between a row's icon and its text. */
  sm: SPACING_SCALE[3],
  /** 10pt. Between adjacent chips or short inline groups. */
  smPlus: SPACING_SCALE[4],
  /** 12pt. The standard gap between sibling rows inside a card. */
  md: SPACING_SCALE[5],
  /**
   * 14pt. **The card's own inner padding** — not a generic step, a specific
   * answer to "how much air does a card give its content", measured off
   * `Stat.tsx`'s `slot` padding and `Section.tsx`'s established rhythm. Use
   * this for a card's `paddingHorizontal`/`paddingVertical`, not `md`/`lg`.
   */
  cardPadding: SPACING_SCALE[6],
  /** 16pt. Between distinct blocks within a screen (a stat row and the card below it). */
  lg: SPACING_SCALE[7],
  /**
   * 20pt. **The screen gutter** — the left/right inset every tab agrees on
   * (`ScreenHeader.tsx`, `workouts.tsx`, `progress.tsx`, `goals.tsx`,
   * `index.tsx`, `food.tsx`, `you.tsx` all used the literal `20` before this
   * ticket). This is the token N498, N506 and N507's shared root cause
   * pointed at: three sibling session-detail screens each independently
   * agreeing (or, for Running, forgetting to agree) on this exact number
   * with no shared name for it.
   */
  gutter: SPACING_SCALE[8],
  /** 24pt. Between major sections of a screen. */
  xl: SPACING_SCALE[9],
  /** 32pt. A large section break — above a screen's first card, say. */
  xxl: SPACING_SCALE[10],
  /** 48pt. Rare — a hero element's own clearance. */
  xxxl: SPACING_SCALE[11],
  /** 64pt. Rarer still — full-bleed empty-state breathing room. */
  huge: SPACING_SCALE[12],
} as const;

/**
 * The radius scale. Same sourcing as {@link Spacing}, from `RADIUS_SCALE`.
 */
export const Radius = {
  /** 8pt. A small control — a chip, a compact button. */
  sm: RADIUS_SCALE[0],
  /** 12pt. A secondary surface — a nested row, a smaller card. */
  md: RADIUS_SCALE[1],
  /**
   * 14pt. **The card radius.** See {@link Spacing.cardPadding}'s note — this
   * is the de facto radius 112 sites already agreed on before this ticket,
   * added to the declared scale rather than fought. Use this for any card,
   * not `md`/`lg`. Also exposed as `Card.radius` in `constants/Card.ts` for
   * call sites that want the card token bundle rather than the raw number.
   */
  card: RADIUS_SCALE[2],
  /** 16pt. A large surface — a sheet, a prominent panel. */
  lg: RADIUS_SCALE[3],
  /** 24pt. The largest non-pill radius — a full-bleed sheet's top corners. */
  xl: RADIUS_SCALE[4],
  /** 999. A pill — fully rounded regardless of height. */
  pill: PILL_RADIUS,
} as const;
