#!/usr/bin/env python3
"""Fail if pnpm's release-age guard has been exempted without a recorded reason.

## The failure this prevents

pnpm 11.17 enforces a 24-hour `minimumReleaseAge` BY DEFAULT — set nowhere in
this repo, invisible to `pnpm config get` (which prints `undefined` for a
defaulted value). It exists for one failure mode: a too-FRESH dependency that
turns out to be compromised or broken and is unpublished within a day.

`expo install --fix` defeats it silently. To install a same-day Expo patch it
writes a `minimumReleaseAgeExclude:` block into `pnpm-workspace.yaml` listing
every affected package — no prompt, no line of output. Measured 2026-09-08
(H15/#950, H17/#952): nine packages, three of them (`@expo/cli`,
`@expo/metro-file-map`, `@expo/ui`) transitive and absent from any
`package.json`, so a diff read only against `package.json` would not have shown
them at all. That block was one commit from landing as an unexamined side
effect of "make the red check green".

**The policy, decided by the board owner on 2026-09-10: keep the 24h guard.**
`check:expo-compat` already tolerates a version pnpm will not yet install
(H15/#953) — it warns while every outdated target is inside the window and
fails the moment one is installable — so a same-day Expo release needs no
exemption at all. The bump simply lands the next day.

This check is what makes that policy hold against a tool that would otherwise
quietly reverse it. An exemption is not forbidden; it is required to be a
DECISION — named, with a reason, in a committed file — rather than an artefact.

## Why a reason is the thing checked

An allowlist of bare package names would be satisfied by the same tool run that
created the problem: `expo install --fix` could write both files if the second
were only a list. A prose reason cannot be generated by a tool that does not
know why it is exempting anything, which is precisely the distinction between
a decision and a side effect.

## Parsing

Deliberately stdlib-only — `verify` needs no Python toolchain, matching
`check:python`'s own reasoning. `pnpm-workspace.yaml`'s list is read with a
line scanner rather than a YAML parser, and it MUST handle quoted scoped keys:
the 2026-09-08 extraction that missed `@expo/cli`, `@expo/metro-file-map` and
`@expo/ui` missed exactly those three because they are written `- "@expo/cli"`
while the rest are bare. `--self-test` holds that case.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WORKSPACE = ROOT / "pnpm-workspace.yaml"
ALLOWLIST = ROOT / ".vola-agent" / "release-age-exemptions.json"

BLOCK_KEY = "minimumReleaseAgeExclude:"
MIN_REASON_CHARS = 20
PLACEHOLDERS = {"todo", "tbd", "temporary", "temp", "fixme", "n/a", "none", "-"}


def parse_exclusions(text: str) -> list[str]:
    """Package names under `minimumReleaseAgeExclude:`, quoted or bare."""
    out: list[str] = []
    inside = False
    for raw in text.splitlines():
        stripped = raw.strip()
        if stripped.startswith("#"):
            continue
        if stripped.startswith(BLOCK_KEY):
            inside = True
            continue
        if inside:
            if not stripped.startswith("- "):
                # Any other key at any indent ends the list.
                if stripped and not stripped.startswith("#"):
                    inside = False
                continue
            name = stripped[2:].strip()
            # `- "@expo/cli"` and `- expo` both occur; the quotes are what a
            # naive extraction trips on, because scoped names need them in YAML.
            if len(name) >= 2 and name[0] == name[-1] and name[0] in "\"'":
                name = name[1:-1]
            if name:
                out.append(name)
    return out


def load_allowlist() -> dict[str, str]:
    if not ALLOWLIST.exists():
        return {}
    try:
        data = json.loads(ALLOWLIST.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        print(f"check-release-age-exemptions: {ALLOWLIST} is not valid JSON — {exc}", file=sys.stderr)
        raise SystemExit(1)
    exemptions = data.get("exemptions", {})
    if not isinstance(exemptions, dict):
        print(f"check-release-age-exemptions: {ALLOWLIST}'s `exemptions` must be an object", file=sys.stderr)
        raise SystemExit(1)
    return exemptions


def problems_for(excluded: list[str], allowed: dict[str, str]) -> list[str]:
    found: list[str] = []
    for pkg in excluded:
        reason = allowed.get(pkg)
        if reason is None:
            found.append(
                f"{pkg} is exempted from pnpm's release-age guard but is not in "
                f"{ALLOWLIST.relative_to(ROOT)} — if this was written by `expo install --fix`, "
                "revert pnpm-workspace.yaml rather than recording it"
            )
        elif not isinstance(reason, str) or len(reason.strip()) < MIN_REASON_CHARS:
            found.append(f"{pkg} has no real reason recorded (needs >= {MIN_REASON_CHARS} characters)")
        elif reason.strip().lower().rstrip(".") in PLACEHOLDERS:
            found.append(f"{pkg}'s reason is a placeholder ({reason.strip()!r})")
    return found


def main() -> int:
    if not WORKSPACE.exists():
        print("check-release-age-exemptions: no pnpm-workspace.yaml — nothing to check")
        return 0
    excluded = parse_exclusions(WORKSPACE.read_text(encoding="utf-8"))
    if not excluded:
        print("check-release-age-exemptions: ok — pnpm's 24h release-age guard is not exempted anywhere")
        return 0
    found = problems_for(excluded, load_allowlist())
    if found:
        print(
            f"check-release-age-exemptions: {len(found)} unrecorded release-age exemption(s).\n"
            "pnpm's 24h guard exists for a too-FRESH dependency that gets unpublished. The\n"
            "policy is to keep it: `check:expo-compat` already tolerates a version pnpm will\n"
            "not yet install, so a same-day Expo patch needs no exemption — it lands tomorrow.",
            file=sys.stderr,
        )
        for line in found:
            print(f"  - {line}", file=sys.stderr)
        return 1
    print(f"check-release-age-exemptions: ok — {len(excluded)} exemption(s), each with a recorded reason")
    return 0


# --------------------------------------------------------------------------
# Self-test. Every case is a real shape this has to get right, and the scoped
# ones are here because a first extraction on 2026-09-08 silently missed them.
# --------------------------------------------------------------------------
SELF_TEST = [
    ("no block at all", "packages:\n  - apps/*\n", [], {}, 0),
    ("bare names", f"{BLOCK_KEY}\n  - expo\n  - expo-router\n", ["expo", "expo-router"], {}, 1),
    (
        "QUOTED SCOPED names — the three a naive extraction missed",
        f'{BLOCK_KEY}\n  - "@expo/cli"\n  - "@expo/metro-file-map"\n  - "@expo/ui"\n',
        ["@expo/cli", "@expo/metro-file-map", "@expo/ui"],
        {},
        1,
    ),
    (
        "single-quoted scoped name",
        f"{BLOCK_KEY}\n  - '@expo/ui'\n",
        ["@expo/ui"],
        {},
        1,
    ),
    (
        "recorded with a real reason passes",
        f"{BLOCK_KEY}\n  - expo\n",
        ["expo"],
        {"expo": "Board owner accepted the same-day 57.0.21 patch on 2026-09-08; reviewed."},
        0,
    ),
    (
        "a placeholder reason is not a reason",
        f"{BLOCK_KEY}\n  - expo\n",
        ["expo"],
        {"expo": "TODO"},
        1,
    ),
    (
        "a too-short reason is not a reason",
        f"{BLOCK_KEY}\n  - expo\n",
        ["expo"],
        {"expo": "needed it"},
        1,
    ),
    (
        "a later key ends the list",
        f"{BLOCK_KEY}\n  - expo\nallowBuilds:\n  - sharp\n",
        ["expo"],
        {},
        1,
    ),
    ("comments inside the block are ignored", f"{BLOCK_KEY}\n  # why\n  - expo\n", ["expo"], {}, 1),
]


def self_test() -> int:
    failures: list[str] = []
    for name, text, want_pkgs, allowed, want_rc in SELF_TEST:
        got = parse_exclusions(text)
        if got != want_pkgs:
            failures.append(f"{name}: parsed {got!r}, expected {want_pkgs!r}")
            continue
        rc = 1 if problems_for(got, allowed) else 0
        if rc != want_rc:
            failures.append(f"{name}: exit {rc}, expected {want_rc}")
    if failures:
        print("check-release-age-exemptions self-test FAILED:", file=sys.stderr)
        for f in failures:
            print(f"  - {f}", file=sys.stderr)
        return 1
    print(f"check-release-age-exemptions self-test ok ({len(SELF_TEST)} cases)")
    return 0


if __name__ == "__main__":
    sys.exit(self_test() if "--self-test" in sys.argv else main())
