#!/usr/bin/env node
/**
 * Turns `assets/brand/icons/*.svg` into a TypeScript map the mobile app can
 * render, so the brand kit stays the source of truth for icon geometry.
 *
 * The alternative was copying 25 icons by hand into a component. This repo
 * already knows how that ends — `scripts/check-brand-copies.mjs` exists because
 * a hand-copied brand component drifted within one commit, and the mitigation
 * at the time was a comment asking the next person to remember.
 *
 * The icons are uniform by construction (all 24×24, all `currentColor`, all
 * stroke 1.8 with round caps), so only the primitives vary. That uniformity is
 * asserted rather than assumed: an icon that breaks it fails the build here
 * instead of rendering wrong on a phone.
 *
 *   node scripts/generate_icons.mjs           # write the file
 *   node scripts/generate_icons.mjs --check   # fail if it is out of date
 *
 * `--check` runs in `verify`, so a brand-kit edit that nobody regenerated is a
 * red build rather than a silent divergence.
 */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(root, 'assets/brand/icons');
const OUT = join(root, 'apps/mobile/components/ui/icons.generated.ts');

/** Attributes every icon must share. A divergent one is a bug in the kit. */
const REQUIRED = { viewBox: '0 0 24 24', 'stroke-width': '1.8' };

const attrs = (tag) =>
  Object.fromEntries([...tag.matchAll(/([\w-]+)="([^"]*)"/g)].map((m) => [m[1], m[2]]));

function parse(name, svg) {
  const root = attrs(svg.match(/<svg[^>]*>/)[0]);
  for (const [k, want] of Object.entries(REQUIRED)) {
    if (root[k] !== want) {
      throw new Error(`${name}.svg: ${k}="${root[k]}", expected "${want}". ` +
        `Icons must be uniform — fix the kit rather than special-casing here.`);
    }
  }
  const out = [];
  for (const m of svg.matchAll(/<(path|circle|rect)\b([^>]*)\/>/g)) {
    const a = attrs(`<x ${m[2]}>`);
    if (m[1] === 'path') out.push({ t: 'p', d: a.d });
    else if (m[1] === 'circle') out.push({ t: 'c', cx: +a.cx, cy: +a.cy, r: +a.r });
    else out.push({ t: 'r', x: +a.x, y: +a.y, w: +a.width, h: +a.height, rx: +(a.rx ?? 0) });
  }
  if (!out.length) throw new Error(`${name}.svg: no primitives found`);
  return out;
}

const icons = {};
for (const f of readdirSync(SRC).filter((f) => f.endsWith('.svg')).sort()) {
  const name = f.replace(/\.svg$/, '');
  icons[name] = parse(name, readFileSync(join(SRC, f), 'utf8'));
}

const body = `// GENERATED by scripts/generate_icons.mjs — do not edit.
// Source: assets/brand/icons/*.svg. Run \`node scripts/generate_icons.mjs\`
// after changing the kit; \`verify\` fails if this file is stale.
//
// Every icon is 24×24, stroke 1.8, round caps and joins, and coloured by the
// caller — the kit's \`currentColor\` becomes the \`color\` prop on \`Icon\`.

export type Primitive =
  | { t: 'p'; d: string }
  | { t: 'c'; cx: number; cy: number; r: number }
  | { t: 'r'; x: number; y: number; w: number; h: number; rx: number };

export const BRAND_ICONS = ${JSON.stringify(icons, null, 2)} as const satisfies Record<
  string,
  readonly Primitive[]
>;

export type BrandIconName = keyof typeof BRAND_ICONS;
`;

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(OUT, 'utf8');
  } catch {
    console.error('icons.generated.ts is missing. Run: node scripts/generate_icons.mjs');
    process.exit(1);
  }
  if (current !== body) {
    console.error(
      'icons.generated.ts is out of date with assets/brand/icons/.\n' +
        'Run: node scripts/generate_icons.mjs',
    );
    process.exit(1);
  }
  console.log(`icons.generated.ts is current (${Object.keys(icons).length} icons).`);
} else {
  writeFileSync(OUT, body);
  console.log(`Wrote ${Object.keys(icons).length} icons to ${OUT.replace(root + '/', '')}`);
}
