#!/usr/bin/env node
/**
 * Turns `assets/brand/design-tokens.json`'s `spacing`/`radius`/`pillRadius`
 * arrays and its `motion` scale into files the apps can import, so the brand
 * kit stays the single source of truth for the numbers rather than something
 * `constants/Spacing.ts` restates by hand.
 *
 * TWO outputs, because there are two consumers and they cannot share a format:
 * a TypeScript module for `apps/mobile`, and a CSS custom-property block for
 * `apps/web` (N556). Web had no temporal tokens at all — every one of its 100
 * `transition` utilities ran on Tailwind's default 150ms ease-IN-out, applied
 * uniformly, including to entrances where `ease-out` belongs.
 *
 * `--check` reports WHICH of the two is stale rather than that something is,
 * because with two outputs "stale" stops being a single fact: regenerate after
 * editing one app and the other is silently left behind.
 *
 * Same shape as `scripts/generate_icons.mjs` (see that file's own doc comment
 * for the fuller argument against hand-copying a brand-kit value): this repo
 * already has one incident of a brand value drifting because it lived in two
 * places (`docs/decisions/history.md`'s N183 entry, on the lime hex), and the
 * fix there — a generated file plus a `--check` step in `verify` — is the
 * fix here too, for the same reason. `constants/Colors.ts` is hand-tokenized
 * rather than generated because colour carries per-value reasoning (contrast
 * ratios, CVD deltas) that a generator can't produce; a bare number scale has
 * none of that, so generating it loses nothing and removes a copy.
 *
 * Why a generated `.ts` file and not `Spacing.ts` importing the JSON
 * directly: `assets/brand/` sits outside `apps/mobile/`, and this repo's Expo
 * app has no `metro.config.js` widening Metro's default watch roots to reach
 * a sibling package's asset directory — unlike `node_modules` resolution,
 * which pnpm workspaces and Expo's monorepo detection already handle, an
 * arbitrary JSON file two levels up is not something the bundler is known to
 * resolve here, and this ticket did not add a metro.config.js to find out.
 * A generated file inside `apps/mobile` is resolved exactly the same way
 * every other local import already is.
 *
 *   node scripts/generate_design_tokens.mjs           # write the file
 *   node scripts/generate_design_tokens.mjs --check   # fail if out of date
 *
 * `--check` runs in `verify`, matching `check:icons`'s own wiring — neither
 * runs as a dedicated CI job step today (both are local-`verify`-only, an
 * existing asymmetry this script does not introduce), so `pnpm run verify`
 * is what actually catches drift here, not a CI job by itself.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(root, 'assets/brand/design-tokens.json');
const OUT = join(root, 'apps/mobile/constants/designTokens.generated.ts');
const OUT_WEB = join(root, 'apps/web/src/app/motion.generated.css');

const tokens = JSON.parse(readFileSync(SRC, 'utf8'));

for (const key of ['spacing', 'radius', 'pillRadius', 'motion']) {
  if (!(key in tokens)) {
    throw new Error(`assets/brand/design-tokens.json is missing "${key}" — generator and file have diverged.`);
  }
}

for (const key of ['duration', 'easing']) {
  if (!(key in tokens.motion)) {
    throw new Error(`assets/brand/design-tokens.json is missing "motion.${key}" — generator and file have diverged.`);
  }
}

// An easing is four control points or it is not a cubic-bezier. Caught here
// rather than in a browser, where a malformed `cubic-bezier()` is simply
// ignored and the transition silently falls back to the default curve.
for (const [name, points] of Object.entries(tokens.motion.easing)) {
  if (!Array.isArray(points) || points.length !== 4 || points.some((n) => typeof n !== 'number')) {
    throw new Error(`assets/brand/design-tokens.json: motion.easing.${name} must be four numbers, got ${JSON.stringify(points)}`);
  }
}

const banner = `// GENERATED by scripts/generate_design_tokens.mjs — do not edit.
// Source: assets/brand/design-tokens.json. Run \`node scripts/generate_design_tokens.mjs\`
// after changing the scale; \`verify\` fails if this file is stale.
//
// Raw numbers only — \`constants/Spacing.ts\` and \`constants/Typography.ts\` are
// where these get names and doc comments. Nothing outside those two files
// should import this module directly.
`;

const body = `
export const SPACING_SCALE = ${JSON.stringify(tokens.spacing)} as const;
export const RADIUS_SCALE = ${JSON.stringify(tokens.radius)} as const;
export const PILL_RADIUS = ${JSON.stringify(tokens.pillRadius)};
export const DURATION = ${JSON.stringify(tokens.motion.duration)} as const;
export const EASING_BEZIER = ${JSON.stringify(tokens.motion.easing)} as const;
`;

const generated = banner + body;

// `inOut` -> `in-out`: the JSON is camelCase because it is read by JS, the
// custom properties are kebab-case because they are read by CSS.
const kebab = (name) => name.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

const webBanner = `/* GENERATED by scripts/generate_design_tokens.mjs — do not edit.
   Source: assets/brand/design-tokens.json. Run \`node scripts/generate_design_tokens.mjs\`
   after changing the scale; \`verify\` fails if this file is stale.

   Imported by globals.css. Deliberately UNLAYERED and :root-only — it declares
   custom properties and no rules, so it cannot win or lose a cascade fight, and
   it does not disturb the layer order globals.css sets up for Clerk. */
`;

const webBody = [
  ':root {',
  ...Object.entries(tokens.motion.duration).map(([name, ms]) => `  --duration-${kebab(name)}: ${ms}ms;`),
  ...Object.entries(tokens.motion.easing).map(
    ([name, pts]) => `  --ease-${kebab(name)}: cubic-bezier(${pts.join(', ')});`,
  ),
  '}',
  '',
].join('\n');

const generatedWeb = webBanner + webBody;

const targets = [
  { path: OUT, content: generated },
  { path: OUT_WEB, content: generatedWeb },
];

if (process.argv.includes('--check')) {
  // Collect every stale file rather than exiting on the first: with two
  // outputs, reporting only the first one to differ sends you round the loop
  // twice for a single edit.
  const stale = [];
  for (const { path, content } of targets) {
    let current;
    try {
      current = readFileSync(path, 'utf8');
    } catch {
      stale.push(`${path} does not exist`);
      continue;
    }
    if (current !== content) stale.push(`${path} is stale`);
  }
  if (stale.length > 0) {
    for (const line of stale) console.error(line);
    console.error('Relative to assets/brand/design-tokens.json. Run: node scripts/generate_design_tokens.mjs');
    process.exit(1);
  }
  console.log('designTokens.generated.ts and motion.generated.css are up to date.');
  process.exit(0);
}

for (const { path, content } of targets) {
  writeFileSync(path, content);
  console.log(`Wrote ${path}`);
}
