#!/usr/bin/env node
/**
 * Generate Expo Router's typed routes, so `tsc` can check route literals.
 *
 * ## Why this exists
 *
 * `apps/mobile` has `experiments.typedRoutes: true`, and `tsconfig.json`
 * already includes `.expo/types/**\/*.ts`. So the type checking is configured,
 * correct, and — in CI — checking nothing, because **the file it needs is
 * generated by the Metro dev server into a gitignored directory.** A clean
 * checkout has no `.expo/`, `tsc` falls back to a loose `Href`, and every route
 * literal in the app passes unread.
 *
 * That shipped a bug: `app/food/target.tsx` pushed `/profile`, a route this app
 * has never had, and the only button on a screen whose job is to unblock the
 * athlete landed on `+not-found` (N32). It surfaced only because one worktree
 * happened to be carrying a `router.d.ts` from an earlier dev run. A check that
 * is real on the machine that wrote the code and absent on the machine that
 * gates it is worse than no check, because the repo reads as covered.
 *
 * ## Why it starts a dev server
 *
 * Because nothing else generates them, and that was established by testing
 * rather than assumed:
 *
 *  - **There is no `expo typegen`.** The generator lives at
 *    `@expo/cli/build/src/start/server/type-generation/routes.js` and is called
 *    from `MetroBundlerDevServer`. It is not a CLI command in SDK 57.
 *  - **`expo export` does NOT write them.** Measured: a full
 *    `--platform ios` export completes in ~21s and leaves `.expo/types` absent.
 *  - **Calling the internal module directly is not resolvable.** `@expo/cli` is
 *    a transitive dependency under pnpm's strict layout, so a script in
 *    `apps/mobile` cannot `require` it without reaching through another
 *    package's `node_modules` — and it is unexported build output that can move
 *    between patch releases.
 *
 * So: start the server, wait for the file, stop the server. Measured at 3.5s
 * locally and 5.5s on a CI runner. It is a supported entry point doing the thing it normally
 * does, which is the most durable of the options above.
 *
 * ## What it deliberately does
 *
 * **Fails loudly if the file never appears.** A generator that quietly produces
 * nothing would restore the exact silence it exists to end — `tsc` would go
 * back to a loose `Href` and CI would stay green. The timeout is an error, not
 * a warning.
 *
 * **Picks a port unlikely to collide.** Several dev servers run on this repo's
 * machines at once (8081, and whatever a session has pinned); 8099 is out of
 * that range, and `--port` is honoured before any bind.
 *
 * **Carries the IPv4 flag.** `apps/mobile/package.json`'s scripts all prefix
 * `NODE_OPTIONS=--dns-result-order=ipv4first`, because Node resolves
 * `localhost` to IPv6 first and Metro then binds a socket the client never
 * reaches. Invoking the CLI directly skips those scripts, so the flag is set
 * here — see the Metro entry in CLAUDE.md.
 */

import { spawn } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const MOBILE = join(ROOT, 'apps', 'mobile');
const TYPES = join(MOBILE, '.expo', 'types', 'router.d.ts');
const PORT = '8099';
const TIMEOUT_MS = 120_000;
const POLL_MS = 250;
/**
 * What a COMPLETE file ends with — see the generator's own template.
 *
 * Existence is not completion, and that distinction is the one path back to
 * silent green. `@expo/router-server` composes the whole ~17KB declaration and
 * writes it with a single `writeFileSync`, so between `open(…, 'w')` and the
 * write landing there is a real, if microscopic, window where the file exists
 * and is EMPTY. An empty `.d.ts` is valid TypeScript that declares nothing:
 * `Href` falls back to a loose string, every route literal passes, and CI stays
 * green — restoring precisely the silence this script exists to end.
 *
 * A truncation mid-union would fail closed (the declaration is one long line
 * and would not parse), so the empty case is the dangerous one. Waiting for the
 * closing brace covers both, and costs one read of a small file.
 *
 * The same race is re-armed by the generator's 1s-debounced watcher: a second
 * regeneration in flight when the kill lands can truncate a file already
 * reported as good.
 */
const COMPLETE_SUFFIX = '}';
const MIN_BYTES = 200;

/**
 * Removed first, so a stale file cannot be mistaken for a fresh one.
 *
 * This is the whole reason the bug took as long as it did to find: a
 * `router.d.ts` left over from a dev run predating a rebase reported routes
 * that no longer existed and missed ones that did. Waiting for a file that is
 * already there would reproduce that, in CI, permanently.
 */
function clearStaleTypes() {
  rmSync(TYPES, { force: true });
  mkdirSync(dirname(TYPES), { recursive: true });
}

/** Written, and finished being written. */
function typesAreComplete() {
  if (!existsSync(TYPES)) return false;
  const text = readFileSync(TYPES, 'utf8');
  return text.length > MIN_BYTES && text.trimEnd().endsWith(COMPLETE_SUFFIX);
}

function waitForTypes(child) {
  return new Promise((resolve, reject) => {
    const startedAt = Date.now();
    // Declared before the handlers that close over it. Not a live bug — the
    // executor runs synchronously and `exit` can only fire from a later tick —
    // but the previous order read like one, which invites a worse "fix".
    let timer;
    let log = '';
    const collect = (chunk) => {
      log += chunk.toString();
    };
    child.stdout?.on('data', collect);
    child.stderr?.on('data', collect);

    // If the server dies before the file lands, say so with its output rather
    // than waiting out the full timeout for a process that is already gone.
    child.on('exit', (code) => {
      if (!typesAreComplete()) {
        clearInterval(timer);
        reject(new Error(`Metro exited (code ${code}) before writing types.\n${log}`));
      }
    });

    // Without this, a spawn failure (no `npx` on PATH) is an uncaught
    // exception: still a non-zero exit, but with a raw stack instead of the
    // message below, and the promise never settles.
    child.on('error', (err) => {
      clearInterval(timer);
      reject(new Error(`Could not start Metro: ${err.message}\n${log}`));
    });

    timer = setInterval(() => {
      if (typesAreComplete()) {
        clearInterval(timer);
        resolve(Date.now() - startedAt);
      } else if (Date.now() - startedAt > TIMEOUT_MS) {
        clearInterval(timer);
        reject(new Error(`Timed out after ${TIMEOUT_MS / 1000}s waiting for types.\n${log}`));
      }
    }, POLL_MS);
  });
}

clearStaleTypes();

const child = spawn(
  'npx',
  ['--no-install', 'expo', 'start', '--port', PORT],
  {
    cwd: MOBILE,
    env: { ...process.env, NODE_OPTIONS: '--dns-result-order=ipv4first', CI: '1' },
    stdio: ['ignore', 'pipe', 'pipe'],
    // Its own process GROUP, so the kill below can take Metro's workers with
    // it. Without this, `process.kill(-pid)` has nothing to address and the
    // workers survive holding the port.
    detached: true,
  },
);

let failure = null;
try {
  const ms = await waitForTypes(child);
  console.log(`Route types generated in ${(ms / 1000).toFixed(1)}s → ${TYPES}`);
} catch (err) {
  failure = err;
} finally {
  // `SIGTERM` then the process group: Metro spawns workers, and killing only
  // the parent leaves them holding the port, which turns the NEXT run of this
  // script into a mysterious timeout.
  try {
    process.kill(-child.pid, 'SIGTERM');
  } catch {
    child.kill('SIGTERM');
  }
}

/*
  Exit EXPLICITLY rather than letting the event loop drain.

  Draining requires every process in the group to die and release the piped
  stdio. A Metro worker that traps SIGTERM and lingers would otherwise hang this
  script forever — which wedges `verify` locally, and in CI wedges the Mobile
  job until GitHub's 6-hour default, since no step here sets `timeout-minutes`.
  It fails closed either way; this makes it fail quickly.
*/
if (failure) {
  console.error(`\nCould not generate route types.\n${failure.message}`);
}
process.exit(failure ? 1 : 0);
