#!/usr/bin/env node
/**
 * Turns `assets/brand/design-tokens.json`'s `spacing`/`radius`/`pillRadius`
 * arrays into a TypeScript module the mobile app can import, so the brand kit
 * stays the single source of truth for the numbers rather than something
 * `constants/Spacing.ts` restates by hand.
 *
 * Same shape as `scripts/generate_icons.mjs` (see that file's own doc comment
 * for the fuller argument against hand-copying a brand-kit value): this repo
 * already has one incident of a brand value drifting because it lived in two
 * places (`docs/decisions/history.md`'s N183 entry, on the lime hex), and the
 * fix there — a generated file plus a `--check` step in `verify` — is the
 * fix here too, for the same reason. `constants/Colors.ts` is hand-tokenized
 * rather than generated because colour carries per-value reasoning (contrast
 * ratios, CVD deltas) that a generator can't produce; a bare number scale has
 * none of that, so generating it loses nothing and removes a copy.
 *
 * Why a generated `.ts` file and not `Spacing.ts` importing the JSON
 * directly: `assets/brand/` sits outside `apps/mobile/`, and this repo's Expo
 * app has no `metro.config.js` widening Metro's default watch roots to reach
 * a sibling package's asset directory — unlike `node_modules` resolution,
 * which pnpm workspaces and Expo's monorepo detection already handle, an
 * arbitrary JSON file two levels up is not something the bundler is known to
 * resolve here, and this ticket did not add a metro.config.js to find out.
 * A generated file inside `apps/mobile` is resolved exactly the same way
 * every other local import already is.
 *
 *   node scripts/generate_design_tokens.mjs           # write the file
 *   node scripts/generate_design_tokens.mjs --check   # fail if out of date
 *
 * `--check` runs in `verify`, matching `check:icons`'s own wiring — neither
 * runs as a dedicated CI job step today (both are local-`verify`-only, an
 * existing asymmetry this script does not introduce), so `pnpm run verify`
 * is what actually catches drift here, not a CI job by itself.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(root, 'assets/brand/design-tokens.json');
const OUT = join(root, 'apps/mobile/constants/designTokens.generated.ts');

const tokens = JSON.parse(readFileSync(SRC, 'utf8'));

for (const key of ['spacing', 'radius', 'pillRadius']) {
  if (!(key in tokens)) {
    throw new Error(`assets/brand/design-tokens.json is missing "${key}" — generator and file have diverged.`);
  }
}

const banner = `// GENERATED by scripts/generate_design_tokens.mjs — do not edit.
// Source: assets/brand/design-tokens.json. Run \`node scripts/generate_design_tokens.mjs\`
// after changing the scale; \`verify\` fails if this file is stale.
//
// Raw numbers only — \`constants/Spacing.ts\` and \`constants/Typography.ts\` are
// where these get names and doc comments. Nothing outside those two files
// should import this module directly.
`;

const body = `
export const SPACING_SCALE = ${JSON.stringify(tokens.spacing)} as const;
export const RADIUS_SCALE = ${JSON.stringify(tokens.radius)} as const;
export const PILL_RADIUS = ${JSON.stringify(tokens.pillRadius)};
`;

const generated = banner + body;

if (process.argv.includes('--check')) {
  let current;
  try {
    current = readFileSync(OUT, 'utf8');
  } catch {
    console.error(`${OUT} does not exist. Run: node scripts/generate_design_tokens.mjs`);
    process.exit(1);
  }
  if (current !== generated) {
    console.error(
      `${OUT} is stale relative to assets/brand/design-tokens.json. Run: node scripts/generate_design_tokens.mjs`,
    );
    process.exit(1);
  }
  console.log('designTokens.generated.ts is up to date.');
  process.exit(0);
}

writeFileSync(OUT, generated);
console.log(`Wrote ${OUT}`);
