// GENERATED by scripts/generate_icons.mjs — do not edit.
// Source: assets/brand/icons/*.svg. Run `node scripts/generate_icons.mjs`
// after changing the kit; `verify` fails if this file is stale.
//
// Every icon is 24×24, stroke 1.8, round caps and joins, and coloured by the
// caller — the kit's `currentColor` becomes the `color` prop on `Icon`.

export type Primitive =
  | { t: 'p'; d: string }
  | { t: 'c'; cx: number; cy: number; r: number }
  | { t: 'r'; x: number; y: number; w: number; h: number; rx: number };

export const BRAND_ICONS = {
  "bjj": [
    {
      "t": "c",
      "cx": 12,
      "cy": 5,
      "r": 2.5
    },
    {
      "t": "p",
      "d": "M8 9l4 3 4-3 2 3-3 3v6H9v-6l-3-3 2-3Z"
    },
    {
      "t": "p",
      "d": "M9 16h6"
    }
  ],
  "calendar": [
    {
      "t": "r",
      "x": 3,
      "y": 5,
      "w": 18,
      "h": 16,
      "rx": 2
    },
    {
      "t": "p",
      "d": "M16 3v4M8 3v4M3 10h18"
    }
  ],
  "calories": [
    {
      "t": "p",
      "d": "M13 2s1 4-2 7c-2 2-3 4-3 6a5 5 0 0 0 10 0c0-4-2-7-5-13Z"
    },
    {
      "t": "p",
      "d": "M10 17c0 2 1 3 2 3s2-1 2-3c0-1-1-2-2-3-1 1-2 2-2 3Z"
    }
  ],
  "chart": [
    {
      "t": "p",
      "d": "M4 19V5M4 19h16"
    },
    {
      "t": "p",
      "d": "m7 15 4-4 3 2 5-6"
    }
  ],
  "check": [
    {
      "t": "p",
      "d": "m5 12 4 4L19 6"
    }
  ],
  "dashboard": [
    {
      "t": "r",
      "x": 3,
      "y": 3,
      "w": 7,
      "h": 7,
      "rx": 2
    },
    {
      "t": "r",
      "x": 14,
      "y": 3,
      "w": 7,
      "h": 7,
      "rx": 2
    },
    {
      "t": "r",
      "x": 3,
      "y": 14,
      "w": 7,
      "h": 7,
      "rx": 2
    },
    {
      "t": "r",
      "x": 14,
      "y": 14,
      "w": 7,
      "h": 7,
      "rx": 2
    }
  ],
  "food": [
    {
      "t": "p",
      "d": "M7 3v8M4 3v5a3 3 0 0 0 6 0V3M7 11v10M17 3v18M17 3c3 2 3 7 0 9"
    }
  ],
  "goal": [
    {
      "t": "c",
      "cx": 12,
      "cy": 12,
      "r": 9
    },
    {
      "t": "c",
      "cx": 12,
      "cy": 12,
      "r": 5
    },
    {
      "t": "c",
      "cx": 12,
      "cy": 12,
      "r": 1.5
    }
  ],
  "heart": [
    {
      "t": "p",
      "d": "M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.6l-1-1a5.5 5.5 0 0 0-7.8 7.8l1 1L12 21l7.8-7.6 1-1a5.5 5.5 0 0 0 0-7.8Z"
    }
  ],
  "notification": [
    {
      "t": "p",
      "d": "M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"
    },
    {
      "t": "p",
      "d": "M10 21h4"
    }
  ],
  "nutrition": [
    {
      "t": "p",
      "d": "M12 21c4 0 7-4 7-9a7 7 0 1 0-14 0c0 5 3 9 7 9Z"
    },
    {
      "t": "p",
      "d": "M12 5c1-2 3-3 5-3"
    },
    {
      "t": "p",
      "d": "M9 8c1 1 2 1 3 1s2 0 3-1"
    }
  ],
  "plus": [
    {
      "t": "p",
      "d": "M12 5v14M5 12h14"
    }
  ],
  "profile": [
    {
      "t": "c",
      "cx": 12,
      "cy": 8,
      "r": 4
    },
    {
      "t": "p",
      "d": "M4 21a8 8 0 0 1 16 0"
    }
  ],
  "progress": [
    {
      "t": "p",
      "d": "M4 19V9M10 19V5M16 19v-7M22 19H2"
    }
  ],
  "recovery": [
    {
      "t": "p",
      "d": "M12 21a9 9 0 1 0-9-9"
    },
    {
      "t": "p",
      "d": "M3 4v5h5"
    },
    {
      "t": "p",
      "d": "M12 7v5l3 2"
    }
  ],
  "route": [
    {
      "t": "c",
      "cx": 6,
      "cy": 18,
      "r": 2
    },
    {
      "t": "c",
      "cx": 18,
      "cy": 6,
      "r": 2
    },
    {
      "t": "p",
      "d": "M8 18c6 0 2-10 8-10"
    }
  ],
  "running": [
    {
      "t": "c",
      "cx": 14,
      "cy": 4,
      "r": 2
    },
    {
      "t": "p",
      "d": "M9 21l2-6 3-3 2 4 4 2M7 13l4-4 3 2 3 1"
    }
  ],
  "search": [
    {
      "t": "c",
      "cx": 11,
      "cy": 11,
      "r": 7
    },
    {
      "t": "p",
      "d": "m20 20-4-4"
    }
  ],
  "settings": [
    {
      "t": "c",
      "cx": 12,
      "cy": 12,
      "r": 3
    },
    {
      "t": "p",
      "d": "M19.4 15a1.8 1.8 0 0 0 .4 2l.1.1-2.8 2.8-.1-.1a1.8 1.8 0 0 0-2-.4 1.8 1.8 0 0 0-1.1 1.6V21h-4v-.1A1.8 1.8 0 0 0 8.8 19a1.8 1.8 0 0 0-2 .4l-.1.1-2.8-2.8.1-.1a1.8 1.8 0 0 0 .4-2A1.8 1.8 0 0 0 2.8 13H2v-4h.8A1.8 1.8 0 0 0 4.4 8a1.8 1.8 0 0 0-.4-2l-.1-.1 2.8-2.8.1.1a1.8 1.8 0 0 0 2 .4A1.8 1.8 0 0 0 9.9 2H14v.1A1.8 1.8 0 0 0 15.1 4a1.8 1.8 0 0 0 2-.4l.1-.1L20 6.3l-.1.1a1.8 1.8 0 0 0-.4 2A1.8 1.8 0 0 0 21.1 9h.9v4h-.9a1.8 1.8 0 0 0-1.7 2Z"
    }
  ],
  "sleep": [
    {
      "t": "p",
      "d": "M20 15a8 8 0 0 1-11-11 8 8 0 1 0 11 11Z"
    }
  ],
  "timer": [
    {
      "t": "c",
      "cx": 12,
      "cy": 13,
      "r": 8
    },
    {
      "t": "p",
      "d": "M12 13l3-2M9 2h6"
    }
  ],
  "trophy": [
    {
      "t": "p",
      "d": "M8 4h8v5a4 4 0 0 1-8 0V4Z"
    },
    {
      "t": "p",
      "d": "M10 13v4M14 13v4M8 21h8M6 6H3v2a4 4 0 0 0 4 4M18 6h3v2a4 4 0 0 1-4 4"
    }
  ],
  "water": [
    {
      "t": "p",
      "d": "M12 2s6 7 6 12a6 6 0 0 1-12 0c0-5 6-12 6-12Z"
    }
  ],
  "weight": [
    {
      "t": "r",
      "x": 4,
      "y": 5,
      "w": 16,
      "h": 15,
      "rx": 3
    },
    {
      "t": "p",
      "d": "M8 10a4 4 0 0 1 8 0"
    },
    {
      "t": "p",
      "d": "M12 10l2-2"
    }
  ],
  "workout": [
    {
      "t": "p",
      "d": "M6 9v6M18 9v6M3 10v4M21 10v4M6 12h12"
    }
  ]
} as const satisfies Record<
  string,
  readonly Primitive[]
>;

export type BrandIconName = keyof typeof BRAND_ICONS;
